// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVx4aTm-RufJisHsMB1RxRHV0_LIU2SKc',
    appId: '1:846945085618:web:9bcceea28eabda96a681ab',
    messagingSenderId: '846945085618',
    projectId: 'voting-app-d9704',
    authDomain: 'voting-app-d9704.firebaseapp.com',
    storageBucket: 'voting-app-d9704.firebasestorage.app',
    measurementId: 'G-B32575ZK8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0tMtBjoUi3I6EWFFJ8gLbogszaV0lBY',
    appId: '1:846945085618:android:430f91aaea210fc2a681ab',
    messagingSenderId: '846945085618',
    projectId: 'voting-app-d9704',
    storageBucket: 'voting-app-d9704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wRTy58dbUwRVGOQY_t9LaLjif6-OWxQ',
    appId: '1:846945085618:ios:6cfe05d148250f2da681ab',
    messagingSenderId: '846945085618',
    projectId: 'voting-app-d9704',
    storageBucket: 'voting-app-d9704.firebasestorage.app',
    iosBundleId: 'com.example.votingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6wRTy58dbUwRVGOQY_t9LaLjif6-OWxQ',
    appId: '1:846945085618:ios:6cfe05d148250f2da681ab',
    messagingSenderId: '846945085618',
    projectId: 'voting-app-d9704',
    storageBucket: 'voting-app-d9704.firebasestorage.app',
    iosBundleId: 'com.example.votingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVx4aTm-RufJisHsMB1RxRHV0_LIU2SKc',
    appId: '1:846945085618:web:b356bfd22c376615a681ab',
    messagingSenderId: '846945085618',
    projectId: 'voting-app-d9704',
    authDomain: 'voting-app-d9704.firebaseapp.com',
    storageBucket: 'voting-app-d9704.firebasestorage.app',
    measurementId: 'G-GGY2MQ0Z7T',
  );
}
